### ISSUE TITLE
How do I get the orderedPoints_filename.txt file

### ISSUE THREAD

**Issue by YY2222222222** [Gabrielcb/Unsupervised_selfAdaptative_ReID#2]
![image](https://user-images.githubusercontent.com/29629054/222946562-d251aa27-f2dd-49da-b95e-c2d2ac731e5f.png)

**Comment by Gabrielcb** [comment]
Hi,

The _orderedPoints_filename_ has its name assigned to it in line 15 in _Clustering.py_. Then it's used as a parameter of OPTICS algorithm in lines 21 to 23. The OPTICS code will put the ordered feature vectors along with the respective reachbilities in the _orderedPoints_filename_ file passed as argument, then the program will load it o get the feature vectors and the reachabilities. So, this file is going to be fulfilled automatically when the lines 21 to 23 are executed. 

Hope this answer helps you,
Cheers

**Comment by duxx222** [comment]
Thank you very much!
